pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "NotGrindstone"

[
        '1.21.11',
        '26.1',
        '26.1.1',
        '26.1.2',
        '26.2',
        '26.3',
].each { version ->
    include ":versions:${version}"
    project(":versions:${version}").projectDir = file("versions/${version}")
}

include ':Plugin'
['1.21.11', '26.1', '26.2', '26.3'].each { version ->
    include ":Plugin:${version}"
    project(":Plugin:${version}").projectDir = file("Plugin/versions/${version}")
}
